Pull Request: Keycloak
katsiaryne/cab-aggregator-app pull request #10
Opened 2024-11-04 21:48 UTC by katsiaryne

2024-11-06 20:29 UTC, psidarovich requested changes

2024-11-06 20:29 UTC, psidarovich commented on auth-service/src/main/java/com/software/modsen/authservice/controller/AuthController.java
> +    {
Use valid java code convention. Brace should be on the prev line

2024-11-06 20:29 UTC, psidarovich commented on auth-service/src/main/java/com/software/modsen/authservice/dto/request/UserLoginRequest.java
> +}
What about immutable class?

2024-11-06 20:29 UTC, psidarovich commented on auth-service/src/main/java/com/software/modsen/authservice/dto/request/UserLoginRequest.java
> +}
Here and in other places. It's a good practice to make request|responses immutable

2024-11-06 20:29 UTC, psidarovich commented on auth-service/src/main/java/com/software/modsen/authservice/exception/ServiceUnAvailableException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
502 - BadGateway

2024-11-08 17:31 UTC, KatsiarynaKozlova commented on auth-service/src/main/java/com/software/modsen/authservice/exception/ServiceUnAvailableException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
Fixed

2024-11-08 17:32 UTC, KatsiarynaKozlova commented on auth-service/src/main/java/com/software/modsen/authservice/dto/request/UserLoginRequest.java
> +}
rewrite on records

2024-11-08 17:32 UTC, KatsiarynaKozlova commented on auth-service/src/main/java/com/software/modsen/authservice/controller/AuthController.java
> +    {
Fixed

2024-11-11 16:25 UTC, psidarovich approved these changes

2024-11-11 18:11 UTC, merged